# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
print("Hello World!")


Hello World!


In [1]:
sum(i**3 for i in range(10))


2025

In [2]:
(10**3)

1000

In [8]:
a = np.random.rand(5)
print(f"{a}")
print(f"{a.shape}")
print(f"{a.dtype}")

[0.57676534 0.82692835 0.18040608 0.50483275 0.26460338]
(5,)
float64


In [11]:
a = np.arange(10)
print(f"{a}")
print(f"{a[2:7:1]}")
print(f"{a[2:7:2]}")

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [14]:
a = np.array([1,2,3,4])
print(f"{np.sum(a)}")
print(f"{a**3}")

10
[ 1  8 27 64]


In [18]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")
print(f"Binary operators work element wise: {np.dot(a,b)}")
c=np.dot(a,b)
print(f"{c}, {c.shape}")
d=np.array([9])
print(f"{d}, {d.shape}")


Binary operators work element wise: [0 0 6 8]
Binary operators work element wise: 20
20, ()
[9], (1,)


In [20]:
import numpy as np
import multiprocessing
print("NumPy detected CPU cores:", multiprocessing.cpu_count())



NumPy detected CPU cores: 8
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/84/5079cppj57s0lzywhyz

In [32]:

np.__config__.show()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/84/5079cppj57s0lzywhyzcxkjc0000gn/T/build-env-jexs

In [34]:
m = 2e-2
print(f"{m}")



0.02


In [5]:
import numpy as np

a = np.zeros(4)
print(f"{a}")
print(f"{a.shape}")
a.dtype


[0. 0. 0. 0.]
(4,)


dtype('float64')

In [3]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import os

model_name = "microsoft/Phi-3-mini-4k-instruct"  # seems to be model this macbook manages to handle.
cache_dir = "/Users/jzhang/.cache/huggingface/hub"

# Set Hugging Face cache location
os.environ["HF_HOME"] = cache_dir
os.environ["TRANSFORMERS_CACHE"] = cache_dir

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=cache_dir)
print(f"loaded tokenizer: {tokenizer}")
print(f"{len(tokenizer)}")

loaded tokenizer: LlamaTokenizerFast(name_or_path='microsoft/Phi-3-mini-4k-instruct', vocab_size=32000, model_max_length=4096, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	0: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=False),
	32000: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32001: AddedToken("<|assistant|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32002: AddedToken("<|placeholder1|>", rstrip=True, lstrip=False, single_word=False, normaliz